title: "Language Documentation in Minawao refugee camp"
remote_theme: jekyll/minima@1e8a445

# Pages to show in top navigation
header_pages:
  - index.md
  - about.md
  - streams.md
  - team.md

# Footer, excerpts
show_excerpts: true

# Optional: enable GitHub Pages blog behavior off
paginate: 0
